### ISSUE TITLE
Example asm files?

### ISSUE THREAD

**Issue by armaray** [GrenDrake/ggasm#1]
Hi GrenDrake,
your project is very intresting for me. Can you give test / example files for your asm format. Extracting this from the source is hard to do.

**Comment by GrenDrake** [comment]
Sure, I should be able to do that tonight.

**Comment by GrenDrake** [comment]
Okay, I've added a basic example file (along with a GLK asm header file) . Hopefully it's reasonably clear about how it works.

**Comment by armaray** [comment]
Thanks a lot for quick reaction. IncludeBinary fix/implementation happend during my testing :-)
Error reporting is good, but position of issue (file/line) is missing. Could be info from Token be used?

**Comment by GrenDrake** [comment]
Yes, the position information is one of those things I need to sit down and actually finish up; it's what the information in Token is there for, I just haven't gotten around to doing it.

**Comment by GrenDrake** [comment]
I've done a nearly complete port of the "model.c" sample glk program as a more extensive example; unless there's other specific examples you think would be good, I'm going to close this issue now.
