### ISSUE TITLE
Handling of addressing mode 0 (Constant zero)

### ISSUE THREAD

**Issue by armaray** [GrenDrake/ggasm#4]
I use callf to call global functions without parameters and without return value.

In my own implementation of Glulx code generation (I have a kind of cross compiler) this produces

8160 01 67               callf init  

whereby 00000067 is the address of function init

In Glulx spec callf is defined as   callf L1 S1

How should I tell the assembler, that S1 is address mode 0.
Simply ommitting S1 doesn't work  ( ->  Bad operand count for callf)
callf init 0   is accepted 

Simular situation with return

31 00                    return

Is it needed to write 

return 0 instead to fulfill the spec  ( return L1)  ??

**Comment by GrenDrake** [comment]
Passing a zero for the store operand of callf (or any opcode, really) will discard the result so 

```
callf init 0
```
is correct (or should be at any rate). Return also does require a value even if you know you'll always be discarding it.

**Comment by armaray** [comment]
OK, I adapted my generator accordingly.
