### ISSUE TITLE
named local variables

### ISSUE THREAD

**Issue by armaray** [GrenDrake/ggasm#5]
Do you have plans to allow identifiers for local variables and parameters?
I think readability of code would benefit a lot.

Example of ggasm code generated (not working at this time):
; Function move2Loc( adr loc this )
function move2Loc 3
    div adr 4 sp
    add sp 8 sp
    astore 0 sp loc
    return 0

For correct working i currently have to change to
function move2Loc 3
    div #0 4 sp
    add sp 8 sp
    astore 0 sp #1
    return 0

which makes it much harder to understand.

**Comment by GrenDrake** [comment]
While it's a good idea, I'd like to get the stuff on my TODO list first - there's still quite a few things that need addressed or are entirely unimplemented as yet.

**Comment by armaray** [comment]
That's absolutely OK, it's your project ;-)
As long as I generate the asm file there is no functional disadvantage (might only support error diagnostics for bug fixing).
But when small parts should be written directly in assembler named locals are a great help.

**Comment by armaray** [comment]
Closed by error, enhancement should be active

**Comment by GrenDrake** [comment]
Closing this issue as development on this repository is ending in favour of my rewritten version *glulx-assemble* (which already supports this feature).
