### ISSUE TITLE
Glulx code generated to RAM

### ISSUE THREAD

**Issue by armaray** [GrenDrake/ggasm#6]
I wonder why the code (functions) is generated into RAM. I would have expected this in ROM block.
Any reason for this?

See start of codedump.txt
256/0: [LABEL:_startOfRAM type:BuiltIn localCount:0 @null:0]
256/3: [LABEL:setup type:LocalFunction localCount:0 @null:0]
259/4: [INST 329:[value:2 size:1 name:null mode:Constant][value:0 size:0 name:null mode:Constant]]

This is in line with the size definitions of ROM / RAM of the header.

**Comment by GrenDrake** [comment]
Everything goes into RAM by default. To add something to ROM put it between the **toROM** and **endROM** directives.
